apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  creationTimestamp: null
  labels:
    branch: master
    build: "1"
    jenkins.io/pipelineType: build
    owner: myowner
    repository: myrepo
  name: myowner-myrepo-master-xww7w-1
spec:
  params:
  - name: version
    value: 0.0.1
  pipelineRef:
    apiVersion: tekton.dev/v1alpha1
    name: myowner-myrepo-master-xww7w-1
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}
